// RegisterEdgeCenter.tsx
import { LinkConfig, EdgeTypeMap } from "@/components/graph/interface";
import processCreateFileShipConfig from "@/components/graph/edge/ProcessCreateFileShip";
import processCreateShipConfig from "@/components/graph/edge/ProcessCreateShip";
import processTerminateShipConfig from "@/components/graph/edge/ProcessTerminateShip";
import processAccessShipConfig from "@/components/graph/edge/ProcessAccessShip";
import processNetShipConfig from "@/components/graph/edge/ProcessNetShip";
import processDnsShipConfig from "@/components/graph/edge/ProcessDnsShip";
import netDnsShipConfig from "@/components/graph/edge/NetDnsShip";
import netLateralMovementShipConfig from "@/components/graph/edge/NetLateralMovementShip";
import processAccessVolumeConfig from "@/components/graph/edge/ProcessAccessVolumeShip";
import processDeleteFileShipConfig from "@/components/graph/edge/ProcessDeleteFileShip";
import processReadFileShipConfig from "@/components/graph/edge/ProcessReadFileShip";
import processWriteFileShipConfig from "@/components/graph/edge/ProcessWriteFileShip";
import processSetFileEaShipConfig from "@/components/graph/edge/ProcessSetFileEaShip";
import processRenameFileShipConfig from "@/components/graph/edge/ProcessRenameFileShip";
import renameFilePeerShipConfig from "@/components/graph/edge/RenameFilePeerShip";
import processMoveFileShipConfig from "@/components/graph/edge/ProcessMoveFileShip";
import moveFilePeerShipConfig from "@/components/graph/edge/MoveFilePeerShip";
import processChangeFileAttributesShipConfig from "@/components/graph/edge/ProcessChangeFileAttributesShip";
import processCreateFileStreamShipConfig from "@/components/graph/edge/ProcessCreateFileStreamShip";
import processDeleteFileStreamShipConfig from "@/components/graph/edge/ProcessDeleteFileStreamShip";
import streamPeerFileShipConfig from "@/components/graph/edge/StreamPeerFileShip";
import newFilePeerStreamShipConfig from "@/components/graph/edge/NewFilePeerStreamShip";
import processBitsCreateShipConfig from "@/components/graph/edge/ProcessBitsCreateShip";
import processBitsAddFileShipConfig from "@/components/graph/edge/ProcessBitsAddFileShip";
import processBitsStatusChangeShipConfig from "@/components/graph/edge/ProcessBitsStatusChangeShip";
import processCreateTaskShipConfig from "@/components/graph/edge/ProcessCreateTaskShip";
import taskMd5PeerShipConfig from "@/components/graph/edge/FileTaskImageMd5PeerShip";
import taskLateralMovementShipConfig from "@/components/graph/edge/TaskLateralMovementShip";
import processDeleteTaskShipConfig from "@/components/graph/edge/ProcessDeleteTaskShip";
import processCrossMemoryExecuteShipConfig from "@/components/graph/edge/ProcessCrossMemoryExecuteShip";
import processDllLoadShipConfig from "@/components/graph/edge/ProcessDllLoadShip";
import dllMd5PeerShipConfig from "@/components/graph/edge/FileDllImageMd5PeerShip";
import processDriverLoadShipConfig from "@/components/graph/edge/ProcessDriverLoadShip";
import driverMd5PeerShipConfig from "@/components/graph/edge/FileDriverImageMd5PeerShip";
import processEnDecryptShipConfig from "@/components/graph/edge/ProcessEnDecryptShip";
import processCreateEventShipConfig from "@/components/graph/edge/ProcessCreateEventShip";
import processOpenEventShipConfig from "@/components/graph/edge/ProcessOpenEventShip";
import processCreateFileMappingShipConfig from "@/components/graph/edge/ProcessCreateFileMappingShip";
import processConnectFileMappingShipConfig from "@/components/graph/edge/ProcessConnectFileMappingShip";
import processCreateMailSlotShipConfig from "@/components/graph/edge/ProcessCreateMailSlotShip";
import processConnectMailSlotShipConfig from "@/components/graph/edge/ProcessConnectMailSlotShip";
import processModifyMbrShipConfig from "@/components/graph/edge/ProcessModifyMbrShip";
import processCreatePipeShipConfig from "@/components/graph/edge/ProcessCreatePipeShip";
import processConnectPipeShipConfig from "@/components/graph/edge/ProcessConnectPipeShip";
import processPowershellShipConfig from "@/components/graph/edge/ProcessPowershellShip";
import processCreateRegKeyShipConfig from "@/components/graph/edge/ProcessCreateRegKeyShip";
import processDeleteRegKeyShipConfig from "@/components/graph/edge/ProcessDeleteRegKeyShip";
import processRenameRegKeyShipConfig from "@/components/graph/edge/ProcessRenameRegKeyShip";
import renameRegKeyPeerShipConfig from "@/components/graph/edge/RenameRegKeyPeerShip";
import processSetRegValueShipConfig from "@/components/graph/edge/ProcessSetRegValueShip";
import processDeleteRegValueShipConfig from "@/components/graph/edge/ProcessDeleteRegValueShip";
import processQueryRegValueShipConfig from "@/components/graph/edge/ProcessQueryRegValueShip";
import processStealingCredentialsShipConfig from "@/components/graph/edge/ProcessStealingCredentialsShip";
import processAdjustPrivilegeShipConfig from "@/components/graph/edge/ProcessAdjuestPrivilegeShip";
import processImpersonationTokenShipConfig from "@/components/graph/edge/ProcessImpersonationTokenShip";
import processHookMessageShipConfig from "@/components/graph/edge/ProcessHookMessageShip";
import processSetTokenShipConfig from "@/components/graph/edge/ProcessSetTokenShip";
import processAccessUrlShipConfig from "@/components/graph/edge/ProcessUrlShip";
import processCreateWmiClassShipConfig from "@/components/graph/edge/ProcessCreateWmiClassShip";
import wmiLateralMovementShipConfig from "@/components/graph/edge/WmiLateralMovementShip";
import processQueryWmiShipConfig from "@/components/graph/edge/ProcessQueryWmiShip";
import processExecuteWmiShipConfig from "@/components/graph/edge/ProcessExecuteWmiShip";
import processWmiConsumerShipConfig from "@/components/graph/edge/ProcessWmiConsumerShip";
import processWmiFilterShipConfig from "@/components/graph/edge/ProcessWmiFilterShip";
import consumerFilterBindingShipConfig from "@/components/graph/edge/ConsumerFilterBindingShip";
import deviceAgentShipConfig from "@/components/graph/edge/DeviceChangeShip";
import processCreateServiceShipConfig from "@/components/graph/edge/ProcessCreateServiceShip";
import processStartServiceShipConfig from "@/components/graph/edge/ProcessStartServiceShip";
import processDeleteServiceShipConfig from "@/components/graph/edge/ProcessDeleteServiceShip";
import processStopServiceShipConfig from "@/components/graph/edge/ProcessStopServiceShip";
import processPauseRestoreServiceShipConfig from "@/components/graph/edge/ProcessPauseRestoreServiceShip";
import processChangeServiceShipConfig from "@/components/graph/edge/ProcessChangeServiceShip";
import serviceMd5PeerShipConfig from "@/components/graph/edge/FileServiceImageMd5PeerShip";
import processCreateAccountShipConfig from "@/components/graph/edge/ProcessCreateAccountShip";
import processEnableAccountShipConfig from "@/components/graph/edge/ProcessEnableAccountShip";
import processResetAccountPwdShipConfig from "@/components/graph/edge/ProcessResetAccountPwdShip";
import processDisableAccountShipConfig from "@/components/graph/edge/ProcessDisableAccountShip";
import processDeleteAccountShipConfig from "@/components/graph/edge/ProcessDeleteAccountShip";
import processModifyAccountShipConfig from "@/components/graph/edge/ProcessModifyAccountShip";
import processAddAccountGroupShipConfig from "@/components/graph/edge/ProcessAddAccountGroupShip";
import processDeleteAccountGroupShipConfig from "@/components/graph/edge/ProcessDeleteAccountGroupShip";
import processCreateGroupShipConfig from "@/components/graph/edge/ProcessCreateGroupShip";
import processDeleteGroupShipConfig from "@/components/graph/edge/ProcessDeleteGroupShip";


/** 边注册中心 */
const edgeRegistry: EdgeTypeMap<any> = {};

/** 注册边类型 */
export function registerEdge(type: string, config: LinkConfig<any>) {
  edgeRegistry[type] = config;
}

/** 获取所有注册的边类型 */
export function getEdgeRegistry(): EdgeTypeMap<any> {
  return edgeRegistry;
}

/** 默认注册 */
registerEdge("CREATE_FILE", processCreateFileShipConfig);
registerEdge("CREATE_PROCESS", processCreateShipConfig);
registerEdge("TERMINATE_PROCESS", processTerminateShipConfig);
registerEdge("ACCESS_PROCESS", processAccessShipConfig);
registerEdge("PROCESS_NET", processNetShipConfig);
registerEdge("PROCESS_DNS", processDnsShipConfig);
registerEdge("NET_DNS", netDnsShipConfig);
registerEdge("NET_LATERAL_MOVEMENT", netLateralMovementShipConfig);
registerEdge("ACCESS_VOLUME", processAccessVolumeConfig);
registerEdge("DELETE_FILE", processDeleteFileShipConfig);
registerEdge("READ_FILE", processReadFileShipConfig);
registerEdge("WRITE_FILE", processWriteFileShipConfig);
registerEdge("SET_FILE_EA", processSetFileEaShipConfig);
registerEdge("RENAME_FILE", processRenameFileShipConfig);
registerEdge("RENAME_PEER_FILE", renameFilePeerShipConfig);
registerEdge("MOVE_FILE", processMoveFileShipConfig);
registerEdge("MOVE_PEER_FILE", moveFilePeerShipConfig);
registerEdge("CHANGE_FILE_ATTRIBUTES", processChangeFileAttributesShipConfig);
registerEdge("CREATE_FILE_STREAM", processCreateFileStreamShipConfig);
registerEdge("DELETE_FILE_STREAM", processDeleteFileStreamShipConfig);
registerEdge("STREAM_PEER_FILE", streamPeerFileShipConfig);
registerEdge("NEW_FILE_PEER_STREAM", newFilePeerStreamShipConfig);
registerEdge("CREATE_BITS", processBitsCreateShipConfig);
registerEdge("BITS_ADD_FILE", processBitsAddFileShipConfig);
registerEdge("BITS_STATUS_CHANGE", processBitsStatusChangeShipConfig);
registerEdge("CREATE_TASK", processCreateTaskShipConfig);
registerEdge("FILE_MD5_PEER_SHIP", taskMd5PeerShipConfig);
registerEdge("TASK_LATERAL_MOVEMENT", taskLateralMovementShipConfig);
registerEdge("DELETE_TASK", processDeleteTaskShipConfig);
registerEdge("CROSS_MEMORY_EXECUTE", processCrossMemoryExecuteShipConfig);
registerEdge("LOAD_DLL", processDllLoadShipConfig);
registerEdge("DLL_MD5_PEER_SHIP", dllMd5PeerShipConfig);
registerEdge("LOAD_DRIVER", processDriverLoadShipConfig);
registerEdge("DRIVER_MD5_PEER_SHIP", driverMd5PeerShipConfig);
registerEdge("ENCRYPT_DECRYPT", processEnDecryptShipConfig);
registerEdge("CREATE_EVENT", processCreateEventShipConfig);
registerEdge("OPEN_EVENT", processOpenEventShipConfig);
registerEdge("CREATE_FILE_MAPPING", processCreateFileMappingShipConfig);
registerEdge("CONNECT_FILE_MAPPING", processConnectFileMappingShipConfig);
registerEdge("CREATE_MAILSLOT", processCreateMailSlotShipConfig);
registerEdge("CONNECT_MAILSLOT", processConnectMailSlotShipConfig);
registerEdge("MODIFY_MBR", processModifyMbrShipConfig);
registerEdge("CREATE_PIPE", processCreatePipeShipConfig);
registerEdge("CONNECT_PIPE", processConnectPipeShipConfig);
registerEdge("POWERSHELL", processPowershellShipConfig);
registerEdge("CREATE_REGKEY", processCreateRegKeyShipConfig);
registerEdge("DELETE_REGKEY", processDeleteRegKeyShipConfig);
registerEdge("RENAME_REGKEY", processRenameRegKeyShipConfig);
registerEdge("RENAME_REGKEY_PEER", renameRegKeyPeerShipConfig);
registerEdge("SET_REGVALUE", processSetRegValueShipConfig);
registerEdge("DELETE_REGVALUE", processDeleteRegValueShipConfig);
registerEdge("QUERY_REGVALUE", processQueryRegValueShipConfig);
registerEdge("STEALING_CREDENTIALS", processStealingCredentialsShipConfig);
registerEdge("ADJUST_PRIVILEGE", processAdjustPrivilegeShipConfig);
registerEdge("IMPERSONATION_TOKEN", processImpersonationTokenShipConfig);
registerEdge("HOOK_MESSAGE", processHookMessageShipConfig);
registerEdge("SET_TOKEN", processSetTokenShipConfig);
registerEdge("ACCESS_URL", processAccessUrlShipConfig);
registerEdge("CREATE_WMI_CLASS", processCreateWmiClassShipConfig);
registerEdge("WMI_LATERAL_MOVEMENT", wmiLateralMovementShipConfig);
registerEdge("WMI_QUERY", processQueryWmiShipConfig);
registerEdge("WMI_EXECUTE", processExecuteWmiShipConfig);
registerEdge("WMI_CONSUMER", processWmiConsumerShipConfig);
registerEdge("WMI_FILTER", processWmiFilterShipConfig);
registerEdge("CONSUMER_FILTER_BINDING", consumerFilterBindingShipConfig);
registerEdge("DEVICE_CHANGE", deviceAgentShipConfig);
registerEdge("CREATE_SERVICE", processCreateServiceShipConfig);
registerEdge("START_SERVICE", processStartServiceShipConfig);
registerEdge("DELETE_SERVICE", processDeleteServiceShipConfig);
registerEdge("STOP_SERVICE", processStopServiceShipConfig);
registerEdge("PAUSE_RESTORE_SERVICE", processPauseRestoreServiceShipConfig);
registerEdge("CHANGE_SERVICE", processChangeServiceShipConfig);
registerEdge("SERVICE_MD5_PEER_SHIP", serviceMd5PeerShipConfig);
registerEdge("CREATE_ACCOUNT", processCreateAccountShipConfig);
registerEdge("ENABLE_ACCOUNT", processEnableAccountShipConfig);
registerEdge("RESET_ACCOUNT_PASSWORD", processResetAccountPwdShipConfig);
registerEdge("DISABLE_ACCOUNT", processDisableAccountShipConfig);
registerEdge("DELETE_ACCOUNT", processDeleteAccountShipConfig);
registerEdge("MODIFY_ACCOUNT", processModifyAccountShipConfig);
registerEdge("ADD_ACCOUNT_GROUP", processAddAccountGroupShipConfig);
registerEdge("DELETE_ACCOUNT_GROUP", processDeleteAccountGroupShipConfig);
registerEdge("CREATE_GROUP", processCreateGroupShipConfig);
registerEdge("DELETE_GROUP", processDeleteGroupShipConfig);

export default edgeRegistry;
