import type { AttackGraphDetailCardConfig } from "../attack-graph-detail-config-types";
import {
  formatWmiExecuteTitle,
  formatWmiMethodParameters,
  formatWmiScopeKind,
  renderWmiExplicitCredentialBadge,
  renderWmiExecuteTypeBadge,
  renderWmiMethodParameters,
  renderWmiScopeBadge,
} from "../rules/wmi-detail-rules";

export const WMI_EXECUTE_DETAIL_CONFIG: AttackGraphDetailCardConfig = {
  header: {
    icon: "Code",
    iconTone: "blue",
    title: {
      key: "class_name",
      fallback: "WmiExecute",
      formatValue: formatWmiExecuteTitle,
    },
    badges: [
      {
        key: "class_name",
        customRender: renderWmiExecuteTypeBadge,
      },
      {
        key: "scope_kind",
        customRender: renderWmiScopeBadge,
      },
      {
        key: "has_explicit_credential",
        customRender: renderWmiExplicitCredentialBadge,
      },
    ],
    fields: [
      {
        key: "namespace",
        label: "Namespace",
        icon: "Database",
        iconTone: "slate",
        mono: true,
      },
      {
        key: "occurred_at",
        label: "Occurred",
        icon: "Clock",
        iconTone: "green",
        mono: true,
      },
    ],
  },
  sections: [
    {
      title: "WMI Execution Information",
      icon: "Code",
      tone: "blue",
      columns: 2,
      fields: [
        {
          key: "class_name",
          label: "Class Name",
          icon: "FileText",
          iconTone: "slate",
          bold: true,
        },
        {
          key: "method_name",
          label: "Method Name",
          icon: "Tag",
          iconTone: "orange",
          valueTone: "orange",
          bold: true,
        },
        {
          key: "namespace",
          label: "Namespace",
          icon: "Database",
          iconTone: "slate",
          valueTone: "slate",
          display: "code",
          mono: true,
          copyable: true,
          truncate: true,
          maxLength: 120,
          expandable: true,
          showInPopover: true,
        },
        {
          key: "server_name",
          label: "Server",
          icon: "Server",
          iconTone: "blue",
          mono: true,
        },
        {
          key: "user",
          label: "User",
          icon: "User",
          iconTone: "slate",
          mono: true,
        },
        {
          key: "scope_kind",
          label: "Scope Type",
          icon: "Network",
          iconTone: "orange",
          formatValue: formatWmiScopeKind,
          mono: true,
        },
        {
          key: "process_guid",
          label: "Process GUID",
          icon: "Fingerprint",
          iconTone: "slate",
          valueTone: "slate",
          mono: true,
          copyable: true,
        },
        {
          key: "unique_id",
          label: "ID",
          icon: "Fingerprint",
          iconTone: "slate",
          valueTone: "slate",
          mono: true,
        },
      ],
    },
    {
      title: "Method Parameters",
      icon: "Terminal",
      tone: "blue",
      columns: 1,
      fields: [
        {
          key: "method_parameters",
          label: "Parameters",
          icon: "Terminal",
          iconTone: "cyan",
          valueTone: "cyan",
          display: "code",
          mono: true,
          copyable: true,
          truncate: true,
          maxLength: 160,
          expandable: true,
          showInPopover: true,
          formatValue: formatWmiMethodParameters,
          customRender: renderWmiMethodParameters,
        },
      ],
    },
  ],
};
