import type { AttackGraphDetailCardConfig } from "../attack-graph-detail-config-types";
import {
  formatWmiConsumerContext,
  formatWmiScopeKind,
  renderWmiConsumerContext,
  renderWmiConsumerTypeBadge,
  renderWmiScopeKindValue,
  renderWmiScopeBadge,
} from "../rules/wmi-detail-rules";

export const WMI_CONSUMER_DETAIL_CONFIG: AttackGraphDetailCardConfig = {
  header: {
    icon: "Activity",
    iconTone: "blue",
    title: {
      key: "event_consumer_name",
      fallback: "WmiConsumer",
    },
    badges: [
      {
        key: "event_consumer_name",
        customRender: renderWmiConsumerTypeBadge,
      },
      {
        key: "scope_kind",
        customRender: renderWmiScopeBadge,
      },
    ],
    fields: [
      {
        key: "namespace",
        label: "Namespace",
        icon: "Database",
        iconTone: "slate",
        mono: true,
      },
      {
        key: "occurred_at",
        label: "Occurred",
        icon: "Clock",
        iconTone: "green",
        mono: true,
      },
    ],
  },
  sections: [
    {
      title: "Consumer Information",
      icon: "Activity",
      tone: "blue",
      columns: 2,
      fields: [
        {
          key: "event_consumer_name",
          label: "Consumer Name",
          icon: "Tag",
          iconTone: "slate",
          bold: true,
        },
        {
          key: "class_name",
          label: "Consumer Class",
          icon: "FileText",
          iconTone: "slate",
          bold: true,
        },
        {
          key: "event_consumer_type_description",
          label: "Consumer Type",
          icon: "Tag",
          iconTone: "orange",
          valueTone: "orange",
          mono: true,
        },
        {
          key: "event_consumer_type",
          label: "Type ID",
          icon: "Hash",
          iconTone: "slate",
          valueTone: "slate",
          mono: true,
        },
        {
          key: "namespace",
          label: "Namespace",
          icon: "Database",
          iconTone: "slate",
          valueTone: "slate",
          display: "code",
          mono: true,
          copyable: true,
          truncate: true,
          maxLength: 120,
          expandable: true,
          showInPopover: true,
        },
        {
          key: "server_name",
          label: "Server",
          icon: "Server",
          iconTone: "blue",
          mono: true,
        },
        {
          key: "user",
          label: "User",
          icon: "User",
          iconTone: "slate",
          mono: true,
        },
        {
          key: "scope_kind",
          label: "Scope Type",
          icon: "Network",
          iconTone: "orange",
          formatValue: formatWmiScopeKind,
          customRender: renderWmiScopeKindValue,
          mono: true,
        },
        {
          key: "unique_id",
          label: "ID",
          icon: "Fingerprint",
          iconTone: "slate",
          valueTone: "slate",
          mono: true,
        },
      ],
    },
    {
      title: "Consumer Context",
      icon: "Code",
      tone: "blue",
      columns: 1,
      fields: [
        {
          key: "event_consumer_context",
          label: "Context",
          icon: "Code",
          iconTone: "cyan",
          valueTone: "cyan",
          display: "code",
          mono: true,
          copyable: true,
          truncate: true,
          maxLength: 180,
          expandable: true,
          showInPopover: true,
          formatValue: formatWmiConsumerContext,
          customRender: renderWmiConsumerContext,
        },
      ],
    },
  ],
};
