import type { AttackGraphDetailCardConfig } from "../attack-graph-detail-config-types";
import {
  formatWmiClassAttributes,
  formatWmiScopeKind,
  renderWmiBase64AttributesBadge,
  renderWmiClassAttributes,
  renderWmiClassTypeBadge,
  renderWmiScopeKindValue,
  renderWmiScopeBadge,
  resolveWmiClassAttributesTone,
} from "../rules/wmi-detail-rules";

export const WMI_CLASS_DETAIL_CONFIG: AttackGraphDetailCardConfig = {
  header: {
    icon: "Database",
    iconTone: "blue",
    title: {
      key: "class_name",
      fallback: "WmiClass",
    },
    badges: [
      {
        key: "class_name",
        customRender: renderWmiClassTypeBadge,
      },
      {
        key: "scope_kind",
        customRender: renderWmiScopeBadge,
      },
      {
        key: "class_attributes",
        customRender: renderWmiBase64AttributesBadge,
      },
    ],
    fields: [
      {
        key: "namespace",
        label: "Namespace",
        icon: "Database",
        iconTone: "slate",
        mono: true,
      },
      {
        key: "occurred_at",
        label: "Occurred",
        icon: "Clock",
        iconTone: "green",
        mono: true,
      },
    ],
  },
  sections: [
    {
      title: "Class Information",
      icon: "Database",
      tone: "blue",
      columns: 2,
      fields: [
        {
          key: "class_name",
          label: "Class Name",
          icon: "FileText",
          iconTone: "slate",
          bold: true,
        },
        {
          key: "super_class_name",
          label: "Super Class",
          icon: "GitBranch",
          iconTone: "slate",
          mono: true,
        },
        {
          key: "class_path",
          label: "Class Path",
          icon: "FolderTree",
          iconTone: "cyan",
          valueTone: "cyan",
          display: "code",
          mono: true,
          copyable: true,
          truncate: true,
          maxLength: 120,
          expandable: true,
          showInPopover: true,
        },
        {
          key: "namespace",
          label: "Namespace",
          icon: "Database",
          iconTone: "slate",
          valueTone: "slate",
          display: "code",
          mono: true,
          copyable: true,
          truncate: true,
          maxLength: 120,
          expandable: true,
          showInPopover: true,
        },
        {
          key: "server_name",
          label: "Server",
          icon: "Server",
          iconTone: "blue",
          mono: true,
        },
        {
          key: "user",
          label: "User",
          icon: "User",
          iconTone: "slate",
          mono: true,
        },
        {
          key: "scope_kind",
          label: "Scope Type",
          icon: "Network",
          iconTone: "orange",
          formatValue: formatWmiScopeKind,
          customRender: renderWmiScopeKindValue,
          mono: true,
        },
        {
          key: "unique_id",
          label: "ID",
          icon: "Fingerprint",
          iconTone: "slate",
          valueTone: "slate",
          mono: true,
        },
      ],
    },
    {
      title: "Class Attributes",
      icon: "Code",
      tone: "blue",
      resolveTone: resolveWmiClassAttributesTone,
      defaultCollapsed: true,
      columns: 1,
      fields: [
        {
          key: "class_attributes",
          label: "Attributes",
          icon: "Code",
          iconTone: "cyan",
          valueTone: "cyan",
          display: "code",
          mono: true,
          copyable: true,
          truncate: true,
          maxLength: 160,
          expandable: true,
          showInPopover: true,
          formatValue: formatWmiClassAttributes,
          customRender: renderWmiClassAttributes,
        },
      ],
    },
  ],
};
