export function getAccessControlCopy(locale: string) {
  const zh = locale.toLowerCase().startsWith("zh")

  return zh
    ? {
        pageTitle: "创建访问控制策略",
        pageDescription: "定义访问主体、保护对象和行为规则，并将策略安全应用到目标主机",
        backToList: "返回列表",
        reset: "新建策略",
        resetConfirm: "当前未保存的配置将被清空，确定新建策略吗？",
        steps: [
          { title: "基础信息", description: "策略类型与标识" },
          { title: "策略规则", description: "主体、对象与行为" },
          { title: "目标主机", description: "选择应用范围" },
          { title: "确认下发", description: "复核并提交" },
        ],
        policyType: "策略类型",
        policyTypeHint: "选择要控制的访问对象",
        policyTypes: {
          file: ["文件访问策略", "文件路径与操作权限"],
          registry: ["注册表访问策略", "注册表键与值保护"],
          process: ["进程访问策略", "进程与内存操作控制"],
          network: ["网络访问策略", "方向、端口与地址规则"],
        },
        basicInfo: "基础信息",
        policyName: "策略名称",
        policyNamePlaceholder: "例如：重要文件访问保护",
        version: "版本",
        versionHint: "格式为 X.Y.Z",
        priority: "优先级",
        priorityHint: "0–255，数值越大优先级越高",
        policyReady: "基础信息完整",
        summary: "策略摘要",
        summaryHint: "实时核对当前策略内容",
        configuring: "配置中",
        notConfigured: "未配置",
        subjectCount: "访问主体",
        objectCount: "保护对象",
        ruleCount: "行为规则",
        createAndDispatch: "创建与下发",
        createObject: "创建 Policy Object",
        createObjectHint: "保存到 PMC Catalog，获得 Object ID",
        applyHosts: "应用到目标主机",
        applyHostsHint: "选择 Agent 后创建 APPLY Operation",
        hostsNotSelected: "目标主机尚未选择",
        hostsNotSelectedHint: "创建策略不受影响，下发前必须至少选择 1 台主机。",
        previous: "上一步",
        nextRules: "下一步：配置策略规则",
        nextHosts: "下一步：选择目标主机",
        nextReview: "下一步：确认下发",
        validationFailed: "请完善必填内容",
        basicValidation: "请填写策略名称、正确版本和 0–255 的优先级。",
        ruleValidation: "请至少配置一个有效主体、保护对象和行为规则。",
        networkValidation: "请完整填写网络方向、协议、地址、端口和程序路径。",
        subject: "访问主体",
        subjectHint: "定义哪些 Windows 用户、用户组或进程受本策略约束",
        addSubject: "添加主体",
        exceptions: "例外主体",
        exceptionsHint: "可选；命中的主体不受本策略约束",
        addException: "添加例外",
        noExceptions: "未配置例外主体",
        subjectType: "主体类型",
        subjectTypes: {
          process: "进程",
          windowsuser: "Windows 用户",
          windowsgroup: "Windows 用户组",
        },
        processPaths: "进程路径",
        processPathsPlaceholder: "输入路径后按 Enter，例如 C:\\Program Files\\Office\\*.exe",
        accountName: "名称",
        userName: "用户名",
        groupName: "用户组名",
        sid: "SID",
        sidPlaceholder: "例如 S-1-5-21-...",
        hashes: "Hash（可选）",
        hashValue: "Hash 值",
        addHash: "添加 Hash",
        remove: "删除",
        object: "保护对象",
        objectHints: {
          file: "输入需要保护的文件或目录路径，支持后台定义的通配符",
          registry: "输入需要保护的注册表键路径",
          process: "输入需要保护的进程路径，可附加 Hash 精确匹配",
          network: "定义网络方向、协议、地址、端口及程序范围",
        },
        objectLabels: {
          file: "文件路径",
          registry: "注册表路径",
          process: "进程路径",
          network: "网络范围",
        },
        objectPlaceholders: {
          file: "输入路径后按 Enter，例如 C:\\Confidential\\*.docx",
          registry: "输入路径后按 Enter，例如 HKEY_LOCAL_MACHINE\\Software\\...",
          process: "输入路径后按 Enter，例如 C:\\Windows\\System32\\*.exe",
        },
        rules: "行为规则",
        rulesHint: "每个动作只能配置一次，处理方式直接对应后台 effect 字段",
        addRule: "添加规则",
        noRules: "尚未添加行为规则",
        action: "对象操作",
        effect: "处理方式",
        audit: "记录审计",
        effects: { allow: "允许", block: "阻止", prompt: "提示" },
        actions: {
          new: "新建",
          delete: "删除",
          rename: "重命名",
          move: "移动",
          write: "写入",
          set: "设置",
          open: "打开",
          read: "读取",
          execute: "执行",
          query: "查询",
          enum: "枚举",
          create: "创建进程",
          terminate: "结束进程",
          allocate: "分配内存",
          protect: "修改内存保护",
        },
        network: {
          direction: "方向",
          inbound: "入站",
          outbound: "出站",
          action: "网络动作",
          allow: "允许",
          block: "阻止",
          bypass: "绕过",
          profile: "网络配置文件",
          any: "任意",
          domain: "域",
          private: "专用",
          public: "公用",
          protocol: "协议",
          localPort: "本地端口",
          remotePort: "远程端口",
          localAddress: "本地地址",
          remoteAddress: "远程地址",
          programPath: "程序路径",
          programMd5: "程序 MD5（可选）",
          portHint: "支持单端口、范围、逗号分隔或 any",
          addressHint: "支持 IP、CIDR 或 any",
        },
        hostTitle: "选择目标主机",
        hostHint: "复用基线下发的组织树与主机选择方式；离线主机仍可下发",
        selectedHosts: (count: number) => `已选择 ${count} 台主机`,
        noHosts: "至少选择 1 台目标主机",
        reviewTitle: "确认创建并下发",
        reviewHint: "确认后先创建策略对象，再将同一对象应用到所选主机",
        policyObject: "策略对象",
        targetScope: "目标范围",
        dispatchFlow: "执行流程",
        targetHostCount: "目标主机数",
        offlineHostCount: "离线主机数",
        offlineHint: "离线不阻止下发；Agent 后续上线后可接收策略。",
        confirmDispatch: "确认创建并下发",
        submitting: "正在创建并下发...",
        createSuccess: "策略对象创建成功",
        dispatchSuccess: "下发任务已创建",
        dispatchFailed: "策略已创建，但下发失败；可以直接重试下发，不会重复创建策略对象。",
        retryDispatch: "重试下发",
        operationId: "Operation ID",
        objectId: "Object ID",
        status: "状态",
        resultHint: "后台已接受 APPLY 请求，终端执行结果由 PMC Operation 后续更新。",
        endpoint: "接口",
        loadingHosts: "正在加载主机...",
        loadHostsFailed: "加载主机失败",
        retry: "重试",
        searchHosts: "搜索主机、HostID、IP 或 MAC",
        selectAll: "全选",
        clearSelection: "清空",
        clearSearch: "清除搜索",
        searchResults: (term: string, count: number) => `“${term}” 找到 ${count} 项`,
      }
    : {
        pageTitle: "Create Access Control Policy",
        pageDescription: "Define subjects, protected objects and behavior rules, then safely apply the policy to target hosts",
        backToList: "Back to list",
        reset: "New policy",
        resetConfirm: "Unsaved configuration will be cleared. Create a new policy?",
        steps: [
          { title: "Basic Info", description: "Type and identity" },
          { title: "Policy Rules", description: "Subjects, objects and behavior" },
          { title: "Target Hosts", description: "Select application scope" },
          { title: "Review", description: "Review and dispatch" },
        ],
        policyType: "Policy Type",
        policyTypeHint: "Select the access object to control",
        policyTypes: {
          file: ["File Access Policy", "File paths and operation permissions"],
          registry: ["Registry Access Policy", "Registry key and value protection"],
          process: ["Process Access Policy", "Process and memory operation control"],
          network: ["Network Access Policy", "Direction, port and address rules"],
        },
        basicInfo: "Basic Information",
        policyName: "Policy Name",
        policyNamePlaceholder: "e.g. Confidential File Protection",
        version: "Version",
        versionHint: "Use X.Y.Z format",
        priority: "Priority",
        priorityHint: "0–255; a larger value has higher priority",
        policyReady: "Basic information complete",
        summary: "Policy Summary",
        summaryHint: "Review the current policy as you configure it",
        configuring: "Configuring",
        notConfigured: "Not configured",
        subjectCount: "Subjects",
        objectCount: "Objects",
        ruleCount: "Rules",
        createAndDispatch: "Create and Dispatch",
        createObject: "Create Policy Object",
        createObjectHint: "Save to PMC Catalog and receive an Object ID",
        applyHosts: "Apply to Target Hosts",
        applyHostsHint: "Create an APPLY Operation for selected Agents",
        hostsNotSelected: "No target hosts selected",
        hostsNotSelectedHint: "Policy creation is unaffected, but at least one host is required before dispatch.",
        previous: "Previous",
        nextRules: "Next: Configure Rules",
        nextHosts: "Next: Select Hosts",
        nextReview: "Next: Review",
        validationFailed: "Complete the required fields",
        basicValidation: "Enter a policy name, a valid version, and a priority between 0 and 255.",
        ruleValidation: "Configure at least one valid subject, protected object, and behavior rule.",
        networkValidation: "Complete the network direction, protocol, addresses, ports, and program path.",
        subject: "Access Subjects",
        subjectHint: "Define the Windows users, groups, or processes constrained by this policy",
        addSubject: "Add subject",
        exceptions: "Exception Subjects",
        exceptionsHint: "Optional; matching subjects are excluded from the policy",
        addException: "Add exception",
        noExceptions: "No exception subjects configured",
        subjectType: "Subject Type",
        subjectTypes: { process: "Process", windowsuser: "Windows User", windowsgroup: "Windows Group" },
        processPaths: "Process Paths",
        processPathsPlaceholder: "Enter a path and press Enter, e.g. C:\\Program Files\\Office\\*.exe",
        accountName: "Name",
        userName: "User Name",
        groupName: "Group Name",
        sid: "SID",
        sidPlaceholder: "e.g. S-1-5-21-...",
        hashes: "Hashes (optional)",
        hashValue: "Hash value",
        addHash: "Add hash",
        remove: "Remove",
        object: "Protected Objects",
        objectHints: {
          file: "Enter the file or directory paths to protect; backend wildcard syntax is supported",
          registry: "Enter the registry key paths to protect",
          process: "Enter protected process paths and optionally add exact hashes",
          network: "Define network direction, protocol, addresses, ports, and program scope",
        },
        objectLabels: { file: "File Paths", registry: "Registry Paths", process: "Process Paths", network: "Network Scope" },
        objectPlaceholders: {
          file: "Enter a path and press Enter, e.g. C:\\Confidential\\*.docx",
          registry: "Enter a path and press Enter, e.g. HKEY_LOCAL_MACHINE\\Software\\...",
          process: "Enter a path and press Enter, e.g. C:\\Windows\\System32\\*.exe",
        },
        rules: "Behavior Rules",
        rulesHint: "Each action may be configured once; the handling mode maps directly to backend effect",
        addRule: "Add rule",
        noRules: "No behavior rules added",
        action: "Object Action",
        effect: "Handling Mode",
        audit: "Audit",
        effects: { allow: "Allow", block: "Block", prompt: "Prompt" },
        actions: {
          new: "Create", delete: "Delete", rename: "Rename", move: "Move", write: "Write", set: "Set",
          open: "Open", read: "Read", execute: "Execute", query: "Query", enum: "Enumerate",
          create: "Create Process", terminate: "Terminate Process", allocate: "Allocate Memory", protect: "Change Memory Protection",
        },
        network: {
          direction: "Direction", inbound: "Inbound", outbound: "Outbound", action: "Network Action",
          allow: "Allow", block: "Block", bypass: "Bypass", profile: "Profile", any: "Any", domain: "Domain",
          private: "Private", public: "Public", protocol: "Protocol", localPort: "Local Port",
          remotePort: "Remote Port", localAddress: "Local Address", remoteAddress: "Remote Address",
          programPath: "Program Path", programMd5: "Program MD5 (optional)",
          portHint: "Single port, range, comma-separated list, or any",
          addressHint: "IP, CIDR, or any",
        },
        hostTitle: "Select Target Hosts",
        hostHint: "Uses the same organization tree and host selector as baseline dispatch; offline hosts remain dispatchable",
        selectedHosts: (count: number) => `${count} hosts selected`,
        noHosts: "Select at least one target host",
        reviewTitle: "Review and Dispatch",
        reviewHint: "The policy object is created first, then the same object is applied to selected hosts",
        policyObject: "Policy Object",
        targetScope: "Target Scope",
        dispatchFlow: "Execution Flow",
        targetHostCount: "Target Hosts",
        offlineHostCount: "Offline Hosts",
        offlineHint: "Offline status does not block dispatch; Agents can receive the policy when they reconnect.",
        confirmDispatch: "Create and Dispatch",
        submitting: "Creating and dispatching...",
        createSuccess: "Policy object created",
        dispatchSuccess: "Dispatch operation created",
        dispatchFailed: "The policy was created, but dispatch failed. Retry will not create another policy object.",
        retryDispatch: "Retry dispatch",
        operationId: "Operation ID",
        objectId: "Object ID",
        status: "Status",
        resultHint: "The backend accepted the APPLY request. Endpoint results are updated later by the PMC Operation.",
        endpoint: "Endpoint",
        loadingHosts: "Loading hosts...",
        loadHostsFailed: "Failed to load hosts",
        retry: "Retry",
        searchHosts: "Search hosts, HostID, IP, or MAC",
        selectAll: "Select all",
        clearSelection: "Clear",
        clearSearch: "Clear search",
        searchResults: (term: string, count: number) => `${count} results for “${term}”`,
      }
}

export type AccessControlCopy = ReturnType<typeof getAccessControlCopy>
