// RegisterEdgeCenter.tsx
import { LinkConfig, EdgeTypeMap } from "@/features/attack/graph/interface";
import processCreateFileShipConfig from "@/features/attack/graph/edge/process-create-file-ship";
import processCreateShipConfig from "@/features/attack/graph/edge/process-create-ship";
import processTerminateShipConfig from "@/features/attack/graph/edge/process-terminate-ship";
import processAccessShipConfig from "@/features/attack/graph/edge/process-access-ship";
import processNetShipConfig from "@/features/attack/graph/edge/process-net-ship";
import processDnsShipConfig from "@/features/attack/graph/edge/process-dns-ship";
import netDnsShipConfig from "@/features/attack/graph/edge/net-dns-ship";
import netLateralMovementShipConfig from "@/features/attack/graph/edge/net-lateral-movement-ship";
import processAccessVolumeConfig from "@/features/attack/graph/edge/process-access-volume-ship";
import processDeleteFileShipConfig from "@/features/attack/graph/edge/process-delete-file-ship";
import processReadFileShipConfig from "@/features/attack/graph/edge/process-read-file-ship";
import processWriteFileShipConfig from "@/features/attack/graph/edge/process-write-file-ship";
import processSetFileEaShipConfig from "@/features/attack/graph/edge/process-set-file-ea-ship";
import processRenameFileShipConfig from "@/features/attack/graph/edge/process-rename-file-ship";
import renameFilePeerShipConfig from "@/features/attack/graph/edge/rename-file-peer-ship";
import processMoveFileShipConfig from "@/features/attack/graph/edge/process-move-file-ship";
import moveFilePeerShipConfig from "@/features/attack/graph/edge/move-file-peer-ship";
import processChangeFileAttributesShipConfig from "@/features/attack/graph/edge/process-change-file-attributes-ship";
import processCreateFileStreamShipConfig from "@/features/attack/graph/edge/process-create-file-stream-ship";
import processDeleteFileStreamShipConfig from "@/features/attack/graph/edge/process-delete-file-stream-ship";
import streamPeerFileShipConfig from "@/features/attack/graph/edge/stream-peer-file-ship";
import newFilePeerStreamShipConfig from "@/features/attack/graph/edge/new-file-peer-stream-ship";
import processBitsCreateShipConfig from "@/features/attack/graph/edge/process-bits-create-ship";
import processBitsAddFileShipConfig from "@/features/attack/graph/edge/process-bits-add-file-ship";
import processBitsStatusChangeShipConfig from "@/features/attack/graph/edge/process-bits-status-change-ship";
import processCreateTaskShipConfig from "@/features/attack/graph/edge/process-create-task-ship";
import taskMd5PeerShipConfig from "@/features/attack/graph/edge/file-task-image-md5-peer-ship";
import taskLateralMovementShipConfig from "@/features/attack/graph/edge/task-lateral-movement-ship";
import processDeleteTaskShipConfig from "@/features/attack/graph/edge/process-delete-task-ship";
import processCrossMemoryExecuteShipConfig from "@/features/attack/graph/edge/process-cross-memory-execute-ship";
import processDllLoadShipConfig from "@/features/attack/graph/edge/process-dll-load-ship";
import dllMd5PeerShipConfig from "@/features/attack/graph/edge/file-dll-image-md5-peer-ship";
import processDriverLoadShipConfig from "@/features/attack/graph/edge/process-driver-load-ship";
import driverMd5PeerShipConfig from "@/features/attack/graph/edge/file-driver-image-md5-peer-ship";
import processEnDecryptShipConfig from "@/features/attack/graph/edge/process-en-decrypt-ship";
import processCreateEventShipConfig from "@/features/attack/graph/edge/process-create-event-ship";
import processOpenEventShipConfig from "@/features/attack/graph/edge/process-open-event-ship";
import processCreateFileMappingShipConfig from "@/features/attack/graph/edge/process-create-file-mapping-ship";
import processConnectFileMappingShipConfig from "@/features/attack/graph/edge/process-connect-file-mapping-ship";
import processCreateMailSlotShipConfig from "@/features/attack/graph/edge/process-create-mail-slot-ship";
import processConnectMailSlotShipConfig from "@/features/attack/graph/edge/process-connect-mail-slot-ship";
import processModifyMbrShipConfig from "@/features/attack/graph/edge/process-modify-mbr-ship";
import processCreatePipeShipConfig from "@/features/attack/graph/edge/process-create-pipe-ship";
import processConnectPipeShipConfig from "@/features/attack/graph/edge/process-connect-pipe-ship";
import processPowershellShipConfig from "@/features/attack/graph/edge/process-powershell-ship";
import processCreateRegKeyShipConfig from "@/features/attack/graph/edge/process-create-reg-key-ship";
import processDeleteRegKeyShipConfig from "@/features/attack/graph/edge/process-delete-reg-key-ship";
import processRenameRegKeyShipConfig from "@/features/attack/graph/edge/process-rename-reg-key-ship";
import renameRegKeyPeerShipConfig from "@/features/attack/graph/edge/rename-reg-key-peer-ship";
import processSetRegValueShipConfig from "@/features/attack/graph/edge/process-set-reg-value-ship";
import processDeleteRegValueShipConfig from "@/features/attack/graph/edge/process-delete-reg-value-ship";
import processQueryRegValueShipConfig from "@/features/attack/graph/edge/process-query-reg-value-ship";
import processStealingCredentialsShipConfig from "@/features/attack/graph/edge/process-stealing-credentials-ship";
import processAdjustPrivilegeShipConfig from "@/features/attack/graph/edge/process-adjuest-privilege-ship";
import processImpersonationTokenShipConfig from "@/features/attack/graph/edge/process-impersonation-token-ship";
import processHookMessageShipConfig from "@/features/attack/graph/edge/process-hook-message-ship";
import processSetTokenShipConfig from "@/features/attack/graph/edge/process-set-token-ship";
import processAccessUrlShipConfig from "@/features/attack/graph/edge/process-url-ship";
import processCreateWmiClassShipConfig from "@/features/attack/graph/edge/process-create-wmi-class-ship";
import wmiLateralMovementShipConfig from "@/features/attack/graph/edge/wmi-lateral-movement-ship";
import processQueryWmiShipConfig from "@/features/attack/graph/edge/process-query-wmi-ship";
import processExecuteWmiShipConfig from "@/features/attack/graph/edge/process-execute-wmi-ship";
import processWmiConsumerShipConfig from "@/features/attack/graph/edge/process-wmi-consumer-ship";
import processWmiFilterShipConfig from "@/features/attack/graph/edge/process-wmi-filter-ship";
import consumerFilterBindingShipConfig from "@/features/attack/graph/edge/consumer-filter-binding-ship";
import deviceAgentShipConfig from "@/features/attack/graph/edge/device-change-ship";
import processCreateServiceShipConfig from "@/features/attack/graph/edge/process-create-service-ship";
import processStartServiceShipConfig from "@/features/attack/graph/edge/process-start-service-ship";
import processDeleteServiceShipConfig from "@/features/attack/graph/edge/process-delete-service-ship";
import processStopServiceShipConfig from "@/features/attack/graph/edge/process-stop-service-ship";
import processPauseRestoreServiceShipConfig from "@/features/attack/graph/edge/process-pause-restore-service-ship";
import processChangeServiceShipConfig from "@/features/attack/graph/edge/process-change-service-ship";
import serviceMd5PeerShipConfig from "@/features/attack/graph/edge/file-service-image-md5-peer-ship";
import processCreateAccountShipConfig from "@/features/attack/graph/edge/process-create-account-ship";
import processEnableAccountShipConfig from "@/features/attack/graph/edge/process-enable-account-ship";
import processResetAccountPwdShipConfig from "@/features/attack/graph/edge/process-reset-account-pwd-ship";
import processDisableAccountShipConfig from "@/features/attack/graph/edge/process-disable-account-ship";
import processDeleteAccountShipConfig from "@/features/attack/graph/edge/process-delete-account-ship";
import processModifyAccountShipConfig from "@/features/attack/graph/edge/process-modify-account-ship";
import processAddAccountGroupShipConfig from "@/features/attack/graph/edge/process-add-account-group-ship";
import processDeleteAccountGroupShipConfig from "@/features/attack/graph/edge/process-delete-account-group-ship";
import processCreateGroupShipConfig from "@/features/attack/graph/edge/process-create-group-ship";
import processDeleteGroupShipConfig from "@/features/attack/graph/edge/process-delete-group-ship";


/** 边注册中心 */
const edgeRegistry: EdgeTypeMap<any> = {};

/** 注册边类型 */
export function registerEdge(type: string, config: LinkConfig<any>) {
  edgeRegistry[type] = config;
}

/** 获取所有注册的边类型 */
export function getEdgeRegistry(): EdgeTypeMap<any> {
  return edgeRegistry;
}

/** 默认注册 */
registerEdge("CREATE_FILE", processCreateFileShipConfig);
registerEdge("CREATE_PROCESS", processCreateShipConfig);
registerEdge("TERMINATE_PROCESS", processTerminateShipConfig);
registerEdge("ACCESS_PROCESS", processAccessShipConfig);
registerEdge("PROCESS_NET", processNetShipConfig);
registerEdge("PROCESS_DNS", processDnsShipConfig);
registerEdge("NET_DNS", netDnsShipConfig);
registerEdge("NET_LATERAL_MOVEMENT", netLateralMovementShipConfig);
registerEdge("ACCESS_VOLUME", processAccessVolumeConfig);
registerEdge("DELETE_FILE", processDeleteFileShipConfig);
registerEdge("READ_FILE", processReadFileShipConfig);
registerEdge("WRITE_FILE", processWriteFileShipConfig);
registerEdge("SET_FILE_EA", processSetFileEaShipConfig);
registerEdge("RENAME_FILE", processRenameFileShipConfig);
registerEdge("RENAME_PEER_FILE", renameFilePeerShipConfig);
registerEdge("MOVE_FILE", processMoveFileShipConfig);
registerEdge("MOVE_PEER_FILE", moveFilePeerShipConfig);
registerEdge("CHANGE_FILE_ATTRIBUTES", processChangeFileAttributesShipConfig);
registerEdge("CREATE_FILE_STREAM", processCreateFileStreamShipConfig);
registerEdge("DELETE_FILE_STREAM", processDeleteFileStreamShipConfig);
registerEdge("STREAM_PEER_FILE", streamPeerFileShipConfig);
registerEdge("NEW_FILE_PEER_STREAM", newFilePeerStreamShipConfig);
registerEdge("CREATE_BITS", processBitsCreateShipConfig);
registerEdge("BITS_ADD_FILE", processBitsAddFileShipConfig);
registerEdge("BITS_STATUS_CHANGE", processBitsStatusChangeShipConfig);
registerEdge("CREATE_TASK", processCreateTaskShipConfig);
registerEdge("FILE_MD5_PEER_SHIP", taskMd5PeerShipConfig);
registerEdge("TASK_LATERAL_MOVEMENT", taskLateralMovementShipConfig);
registerEdge("DELETE_TASK", processDeleteTaskShipConfig);
registerEdge("CROSS_MEMORY_EXECUTE", processCrossMemoryExecuteShipConfig);
registerEdge("LOAD_DLL", processDllLoadShipConfig);
registerEdge("DLL_MD5_PEER_SHIP", dllMd5PeerShipConfig);
registerEdge("LOAD_DRIVER", processDriverLoadShipConfig);
registerEdge("DRIVER_MD5_PEER_SHIP", driverMd5PeerShipConfig);
registerEdge("ENCRYPT_DECRYPT", processEnDecryptShipConfig);
registerEdge("CREATE_EVENT", processCreateEventShipConfig);
registerEdge("OPEN_EVENT", processOpenEventShipConfig);
registerEdge("CREATE_FILE_MAPPING", processCreateFileMappingShipConfig);
registerEdge("CONNECT_FILE_MAPPING", processConnectFileMappingShipConfig);
registerEdge("CREATE_MAILSLOT", processCreateMailSlotShipConfig);
registerEdge("CONNECT_MAILSLOT", processConnectMailSlotShipConfig);
registerEdge("MODIFY_MBR", processModifyMbrShipConfig);
registerEdge("CREATE_PIPE", processCreatePipeShipConfig);
registerEdge("CONNECT_PIPE", processConnectPipeShipConfig);
registerEdge("POWERSHELL", processPowershellShipConfig);
registerEdge("CREATE_REGKEY", processCreateRegKeyShipConfig);
registerEdge("DELETE_REGKEY", processDeleteRegKeyShipConfig);
registerEdge("RENAME_REGKEY", processRenameRegKeyShipConfig);
registerEdge("RENAME_REGKEY_PEER", renameRegKeyPeerShipConfig);
registerEdge("SET_REGVALUE", processSetRegValueShipConfig);
registerEdge("DELETE_REGVALUE", processDeleteRegValueShipConfig);
registerEdge("QUERY_REGVALUE", processQueryRegValueShipConfig);
registerEdge("STEALING_CREDENTIALS", processStealingCredentialsShipConfig);
registerEdge("ADJUST_PRIVILEGE", processAdjustPrivilegeShipConfig);
registerEdge("IMPERSONATION_TOKEN", processImpersonationTokenShipConfig);
registerEdge("HOOK_MESSAGE", processHookMessageShipConfig);
registerEdge("SET_TOKEN", processSetTokenShipConfig);
registerEdge("ACCESS_URL", processAccessUrlShipConfig);
registerEdge("CREATE_WMI_CLASS", processCreateWmiClassShipConfig);
registerEdge("WMI_LATERAL_MOVEMENT", wmiLateralMovementShipConfig);
registerEdge("WMI_QUERY", processQueryWmiShipConfig);
registerEdge("WMI_EXECUTE", processExecuteWmiShipConfig);
registerEdge("WMI_CONSUMER", processWmiConsumerShipConfig);
registerEdge("WMI_FILTER", processWmiFilterShipConfig);
registerEdge("CONSUMER_FILTER_BINDING", consumerFilterBindingShipConfig);
registerEdge("DEVICE_CHANGE", deviceAgentShipConfig);
registerEdge("CREATE_SERVICE", processCreateServiceShipConfig);
registerEdge("START_SERVICE", processStartServiceShipConfig);
registerEdge("DELETE_SERVICE", processDeleteServiceShipConfig);
registerEdge("STOP_SERVICE", processStopServiceShipConfig);
registerEdge("PAUSE_RESTORE_SERVICE", processPauseRestoreServiceShipConfig);
registerEdge("CHANGE_SERVICE", processChangeServiceShipConfig);
registerEdge("SERVICE_MD5_PEER_SHIP", serviceMd5PeerShipConfig);
registerEdge("CREATE_ACCOUNT", processCreateAccountShipConfig);
registerEdge("ENABLE_ACCOUNT", processEnableAccountShipConfig);
registerEdge("RESET_ACCOUNT_PASSWORD", processResetAccountPwdShipConfig);
registerEdge("DISABLE_ACCOUNT", processDisableAccountShipConfig);
registerEdge("DELETE_ACCOUNT", processDeleteAccountShipConfig);
registerEdge("MODIFY_ACCOUNT", processModifyAccountShipConfig);
registerEdge("ADD_ACCOUNT_GROUP", processAddAccountGroupShipConfig);
registerEdge("DELETE_ACCOUNT_GROUP", processDeleteAccountGroupShipConfig);
registerEdge("CREATE_GROUP", processCreateGroupShipConfig);
registerEdge("DELETE_GROUP", processDeleteGroupShipConfig);

export default edgeRegistry;
