// 预览环境使用的模拟数据。
// 当真实的 /sensor/analysis/forensic/* 接口不可达时，api 层会回退到这些数据，
// 以便页面在没有后端时也能完整渲染与交互。

import type {
  ForensicArtifactDefinitionItem,
  ForensicEndpointItem,
  ForensicEvidenceItem,
  ForensicTaskItem,
} from "./types"

const now = Math.floor(Date.now() / 1000)

export const mockEndpoints: ForensicEndpointItem[] = [
  {
    endpoint_id: "ep-1001",
    velociraptor_client_id: "C.1a2b3c4d5e6f7a8b",
    hostname: "WIN-DC01",
    fqdn: "win-dc01.corp.local",
    os: "windows",
    arch: "amd64",
    agent_id: "agent-9a1f",
    status: "online",
    last_seen_at: now - 45,
  },
  {
    endpoint_id: "ep-1002",
    velociraptor_client_id: "C.2b3c4d5e6f7a8b9c",
    hostname: "WIN-WKS08",
    fqdn: "win-wks08.corp.local",
    os: "windows",
    arch: "amd64",
    agent_id: "agent-3c7d",
    status: "online",
    last_seen_at: now - 120,
  },
  {
    endpoint_id: "ep-1003",
    velociraptor_client_id: "C.3c4d5e6f7a8b9c0d",
    hostname: "WIN-FILE02",
    fqdn: "win-file02.corp.local",
    os: "windows",
    arch: "amd64",
    agent_id: "",
    status: "offline",
    last_seen_at: now - 7200,
  },
  {
    endpoint_id: "ep-1004",
    velociraptor_client_id: "C.4d5e6f7a8b9c0d1e",
    hostname: "LNX-APP01",
    fqdn: "lnx-app01.corp.local",
    os: "linux",
    arch: "amd64",
    agent_id: "agent-5e2a",
    status: "unknown",
    last_seen_at: now - 300,
  },
  {
    endpoint_id: "ep-1005",
    velociraptor_client_id: "C.5e6f7a8b9c0d1e2f",
    hostname: "WIN-HR15",
    fqdn: "win-hr15.corp.local",
    os: "windows",
    arch: "amd64",
    agent_id: "",
    status: "unknown",
    last_seen_at: now - 5400,
  },
]

export const mockArtifacts: ForensicArtifactDefinitionItem[] = [
  {
    artifact_key: "windows.file.collect",
    name: "Windows 文件采集",
    description: "按路径匹配采集文件，可选上传与哈希计算",
    category: "file",
    platform: "windows",
    enabled: true,
    risk_level: "medium",
    sort_order: 1,
    version: "1.2.0",
    input_schema_json: JSON.stringify({
      fields: [
        {
          key: "paths",
          label: "文件路径",
          type: "string_array",
          required: true,
          maxItems: 64,
          maxLength: 1024,
          description: "每行一个路径，最多 64 个，支持通配符",
          placeholder: "C:\\Windows\\System32\\drivers\\etc\\hosts",
        },
        {
          key: "upload",
          label: "上传文件内容",
          type: "boolean",
          default: true,
          description: "是否将匹配到的文件上传至证据库",
        },
        {
          key: "calculate_hash",
          label: "计算哈希",
          type: "boolean",
          default: true,
          description: "计算 SHA256 / SHA1 / MD5",
        },
      ],
    }),
    default_params_json: JSON.stringify({
      paths: [],
      upload: true,
      calculate_hash: true,
    }),
  },
  {
    artifact_key: "windows.registry.collect",
    name: "Windows 注册表采集",
    description: "采集用户注册表键与值",
    category: "registry",
    platform: "windows",
    enabled: true,
    risk_level: "low",
    sort_order: 2,
    version: "1.1.0",
    input_schema_json: JSON.stringify({
      fields: [
        {
          key: "key_glob",
          label: "注册表键 Glob",
          type: "string",
          required: true,
          maxLength: 2048,
          placeholder: "Software\\Microsoft\\Windows\\CurrentVersion\\Run\\**",
        },
        {
          key: "user_regex",
          label: "用户匹配正则",
          type: "string",
          default: ".",
          maxLength: 512,
        },
      ],
    }),
    default_params_json: JSON.stringify({
      key_glob: "Software\\Microsoft\\Windows\\CurrentVersion\\Run\\**",
      user_regex: ".",
    }),
  },
  {
    artifact_key: "windows.eventlog.collect",
    name: "Windows 事件日志采集",
    description: "解析 Windows EVTX 事件日志",
    category: "eventlog",
    platform: "windows",
    enabled: true,
    risk_level: "high",
    sort_order: 3,
    version: "1.3.0",
    input_schema_json: JSON.stringify({
      fields: [
        {
          key: "evtx_glob",
          label: "EVTX 文件 Glob",
          type: "string",
          default: "%SystemRoot%\\System32\\winevt\\Logs\\*.evtx",
        },
        { key: "channel_regex", label: "通道正则", type: "string", default: "." },
        { key: "id_regex", label: "事件 ID 正则", type: "string", default: "." },
        { key: "path_regex", label: "路径正则", type: "string", default: "." },
        {
          key: "start_date",
          label: "开始时间 (RFC3339)",
          type: "string",
          placeholder: "2026-01-01T00:00:00Z",
        },
        {
          key: "end_date",
          label: "结束时间 (RFC3339)",
          type: "string",
          placeholder: "2026-02-01T00:00:00Z",
        },
        {
          key: "vss_analysis_age",
          label: "卷影分析天数",
          type: "number",
          default: 0,
          min: 0,
          max: 30,
        },
      ],
    }),
    default_params_json: JSON.stringify({
      evtx_glob: "%SystemRoot%\\System32\\winevt\\Logs\\*.evtx",
      channel_regex: ".",
      id_regex: ".",
      path_regex: ".",
      vss_analysis_age: 0,
    }),
  },
  {
    artifact_key: "windows.prefetch.collect",
    name: "Windows Prefetch 采集",
    description: "采集 Prefetch 执行痕迹",
    category: "other",
    platform: "windows",
    enabled: false,
    risk_level: "low",
    sort_order: 4,
    version: "1.0.0",
  },
]

export const mockTasks: ForensicTaskItem[] = [
  {
    task_id: "task-8f21",
    endpoint_id: "ep-1001",
    agent_id: "agent-9a1f",
    velociraptor_client_id: "C.1a2b3c4d5e6f7a8b",
    artifact_key: "windows.file.collect",
    artifact_name: "Windows 文件采集",
    task_type: "collect_file",
    status: "success",
    remote_flow_id: "F.CQ1234ABC",
    primary_artifact_id: "ev-5501",
    created_by: "analyst-01",
    created_at: now - 3600,
    started_at: now - 3595,
    finished_at: now - 3540,
    last_sync_at: now - 3530,
  },
  {
    task_id: "task-7d02",
    endpoint_id: "ep-1002",
    agent_id: "agent-3c7d",
    velociraptor_client_id: "C.2b3c4d5e6f7a8b9c",
    artifact_key: "windows.registry.collect",
    artifact_name: "Windows 注册表采集",
    task_type: "collect_registry",
    status: "running",
    remote_flow_id: "F.CQ5678DEF",
    created_by: "analyst-01",
    created_at: now - 300,
    started_at: now - 295,
    last_sync_at: now - 60,
  },
  {
    task_id: "task-6b93",
    endpoint_id: "ep-1005",
    velociraptor_client_id: "C.5e6f7a8b9c0d1e2f",
    artifact_key: "windows.eventlog.collect",
    artifact_name: "Windows 事件日志采集",
    task_type: "collect_eventlog",
    status: "pending",
    created_by: "analyst-02",
    created_at: now - 90,
  },
  {
    task_id: "task-5a44",
    endpoint_id: "ep-1003",
    velociraptor_client_id: "C.3c4d5e6f7a8b9c0d",
    artifact_key: "windows.file.collect",
    artifact_name: "Windows 文件采集",
    task_type: "collect_file",
    status: "failed",
    error_code: "DISPATCH_FAILED",
    error_msg: "客户端离线，Velociraptor 下发超时",
    created_by: "analyst-02",
    created_at: now - 1800,
    started_at: now - 1795,
    finished_at: now - 1500,
    last_sync_at: now - 1490,
  },
]

export const mockEvidence: ForensicEvidenceItem[] = [
  {
    artifact_id: "ev-5501",
    task_id: "task-8f21",
    endpoint_id: "ep-1001",
    agent_id: "agent-9a1f",
    artifact_key: "windows.file.collect",
    artifact_type: "file",
    source_path: "C:\\Windows\\System32\\drivers\\etc\\hosts",
    file_name: "hosts",
    storage_uri: "vfs://clients/C.1a2b3c4d5e6f7a8b/uploads/hosts",
    sha256:
      "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    sha1: "da39a3ee5e6b4b0d3255bfef95601890afd80709",
    md5: "d41d8cd98f00b204e9800998ecf8427e",
    size: 824,
    content_type: "text/plain",
    created_at: now - 3540,
  },
  {
    artifact_id: "ev-5502",
    task_id: "task-8f21",
    endpoint_id: "ep-1001",
    agent_id: "agent-9a1f",
    artifact_key: "windows.file.collect",
    artifact_type: "file_metadata",
    source_path: "C:\\Users\\admin\\Desktop\\report.docx",
    file_name: "report.docx",
    size: 20480,
    sha256:
      "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08",
    created_at: now - 3542,
  },
]

