import type { ForensicOverviewViewModel } from "./types"

export const mockForensicOverview: ForensicOverviewViewModel = {
  availability: {
    level: "partial",
    title: "取证能力部分可用",
    summary:
      "当前有 5 台目标终端，2 台可直接下发取证；2 台未绑定 Agent；1 台离线或状态未知；1 个任务失败需要处理。",
    can_create_task: true,
    target_agent_count: 5,
    available_endpoint_count: 2,
    unbound_endpoint_count: 2,
    offline_endpoint_count: 1,
    blocked_endpoint_count: 3,
    enabled_artifact_count: 3,
    running_task_count: 1,
    failed_task_count: 1,
    blocking_reasons: [
      {
        type: "endpoint_unbound",
        level: "warning",
        text: "2 台终端未绑定 Agent，暂不能直接下发取证。",
      },
      {
        type: "task_failed",
        level: "error",
        text: "1 个取证任务失败，需要进入任务中心查看原因。",
        action_label: "查看",
        action_href: "/frame/investigation/tasks?status=failed",
      },
    ],
  },
  metrics: {
    endpoint_total: 5,
    endpoint_online: 2,
    endpoint_unbound: 2,
    artifact_enabled: 3,
    task_running: 1,
    task_failed: 1,
    evidence_total: 2,
  },
  endpoint_summary: {
    total: 5,
    online: 2,
    offline: 1,
    unknown: 0,
    unbound: 2,
    latest_seen_at: 1782981738,
  },
  task_summary: {
    pending: 1,
    running: 1,
    success: 2,
    failed: 1,
    timeout: 0,
    canceled: 0,
  },
  artifact_summary: {
    total_enabled: 3,
    by_category: {
      file: 1,
      registry: 1,
      eventlog: 1,
      ntfs: 0,
      application: 0,
      forensic: 0,
    },
    high_risk_count: 1,
  },
  evidence_summary: {
    total: 2,
    latest_created_at: 1782980460,
  },
  recent_tasks: [
    {
      task_id: "FT-20260702-001",
      status: "running",
      artifact_key: "windows.file.collect",
      artifact_name: "采集文件",
      target_label: "agent-win-001",
      created_at: 1782981000,
      last_sync_at: 1782981600,
    },
    {
      task_id: "FT-20260702-002",
      status: "success",
      artifact_key: "windows.registry.collect",
      artifact_name: "注册表采集",
      target_label: "agent-win-003",
      created_at: 1782980000,
      last_sync_at: 1782980460,
    },
    {
      task_id: "FT-20260702-003",
      status: "failed",
      artifact_key: "windows.eventlog.collect",
      artifact_name: "事件日志采集",
      target_label: "agent-srv-002",
      created_at: 1782978000,
      last_sync_at: 1782978960,
      error_msg: "客户端离线，Velociraptor 下发超时",
    },
    {
      task_id: "FT-20260702-004",
      status: "success",
      artifact_key: "windows.file.collect",
      artifact_name: "采集文件",
      target_label: "agent-win-001",
      created_at: 1782976000,
      last_sync_at: 1782976500,
    },
    {
      task_id: "FT-20260702-005",
      status: "pending",
      artifact_key: "windows.ntfs.mft",
      artifact_name: "NTFS MFT 采集",
      target_label: "agent-win-003",
      created_at: 1782975000,
    },
  ],
  notices: [
    {
      id: "failed_task",
      level: "error",
      title: "1 个任务失败，需要进入任务中心查看错误。",
      action_label: "查看",
      action_href: "/frame/investigation/tasks?status=failed",
    },
    {
      id: "many_unbound_endpoint",
      level: "warning",
      title: "2 个终端未绑定，暂不能直接下发取证。",
    },
  ],
  last_refresh_at: 1782981738,
}
