"use client"

import { PROCESS_CREATE_HEADER, PROCESS_CREATE_CARD } from "./processCreateConfig"
import { PROCESS_EXIT_HEADER, PROCESS_EXIT_CARD } from "./processExitConfig"
import { PROCESS_ACCESS_HEADER, PROCESS_ACCESS_CARD } from "./processAccessConfig"
import { REMOTE_THREAD_HEADER, REMOTE_THREAD_CARD } from "./remoteThreadConfig"
import { CROSS_MEMORY_EXECUTE_HEADER, CROSS_MEMORY_EXECUTE_CARD } from "./crossMemoryExecuteConfig"
import { DNS_HEADER, DNS_CARD } from "./dnsConfig"
import { NET_COMMUNICATE_HEADER, NET_COMMUNICATE_CARD } from "./netComunicateConfig"
import { SERVICE_CREATE_HEADER, SERVICE_CREATE_CARD } from "./serviceCreateConfig"
import { SERVICE_START_HEADER,SERVICE_START_CARD } from "./serviceStartConfig"
import { SERVICE_DELETE_HEADER, SERVICE_DELETE_CARD } from "./serviceDeleteConfig"
import { SERVICE_STOP_HEADER, SERVICE_STOP_CARD } from "./serviceStopConfig"
import { SERVICE_CONFIG_HEADER, SERVICE_CONFIG_CARD } from "./serviceConfigConfig"
import { SERVICE_PAUSE_HEADER, SERVICE_PAUSE_CARD } from "./servicePauseConfig"
import { DEVICE_CHANGE_HEADER, DEVICE_CHANGE_CARD } from "./deviceChangeConfig"
import { DRIVER_IMAGE_LOAD_HEADER, DRIVER_IMAGE_LOAD_CARD } from "./driverImageLoadConfig"
import { DLL_IMAGE_LOAD_HEADER, DLL_IMAGE_LOAD_CARD } from "./dllImageLoadConfig"
import { TASK_CREATE_HEADER, TASK_CREATE_CARD } from "./taskCreateConfig"
import { TASK_DELETE_HEADER, TASK_DELETE_CARD } from "./taskDeleteConfig"
import { WMI_QUERY_HEADER, WMI_QUERY_CARD } from "./wmiQueryConfig"
import { WMI_CREATE_CLASS_HEADER, WMI_CREATE_CLASS_CARD } from "./wmiCreateClassConfig"
import { WMI_FILTER_HEADER, WMI_FILTER_CARD } from "./wmiFilterConfig"
import { WMI_CONSUMER_HEADER, WMI_CONSUMER_CARD } from "./wmiConsumerConfig"
import { WMI_BINDING_HEADER, WMI_BINDING_CARD } from "./wmiBindingConfig"
import { WMI_EXECUTE_HEADER, WMI_EXECUTE_CARD } from "./wmiExecuteConfig"
import { BITS_CREATE_JOB_HEADER, BITS_CREATE_JOB_CARD } from "./bitsCreateJobConfig"
import { BITS_JOB_ADD_FILE_HEADER, BITS_JOB_ADD_FILE_CARD } from "./bitsJobAddFileConfig"
import { BITS_JOB_CHANGE_STATE_HEADER, BITS_JOB_CHANGE_STATE_CARD } from "./bitsJobChangeStateConfig"
import { WINDOWS_MESSAGE_HOOK_HEADER, WINDOWS_MESSAGE_HOOK_CARD } from "./windowsMessageHookConfig"
import { ENCRYPT_DECRYPT_HEADER, ENCRYPT_DECRYPT_CARD } from "./encryptDecryptConfig"
import { TOKEN_ADJUST_PRIVILEGE_HEADER, TOKEN_ADJUST_PRIVILEGE_CARD } from "./tokenAdjustPrivilegeConfig"
import { TOKEN_IMPERSONATION_HEADER, TOKEN_IMPERSONATION_CARD } from "./tokenImpersonationConfig"
import { CREATE_PROCESS_SET_TOKEN_HEADER, CREATE_PROCESS_SET_TOKEN_CARD } from "./createProcessSetTokenConfig"
import { STEALING_CREDENTIALS_HEADER, STEALING_CREDENTIALS_CARD } from "./stealingCredentialsConfig"
import { FILE_CREATE_HEADER, FILE_CREATE_CARD } from "./fileCreateConfig"
import { FILE_DELETE_HEADER, FILE_DELETE_CARD } from "./fileDeleteConfig"
import { FILE_CHANGE_ATTRIBUTES_HEADER, FILE_CHANGE_ATTRIBUTES_CARD } from "./fileChangeAttributesConfig"
import { FILE_RENAME_HEADER, FILE_RENAME_CARD } from "./fileRenameConfig"
import { FILE_MOVE_HEADER, FILE_MOVE_CARD } from "./fileMoveConfig"
import { FILE_READ_HEADER, FILE_READ_CARD } from "./fileReadConfig"
import { FILE_WRITE_HEADER, FILE_WRITE_CARD } from "./fileWriteConfig"
import { FILE_SET_EA_HEADER, FILE_SET_EA_CARD } from "./fileSetEaConfig"
import { FILE_STREAM_CREATE_HEADER, FILE_STREAM_CREATE_CARD } from "./fileStreamCreateConfig"
import { FILE_STREAM_DELETE_HEADER, FILE_STREAM_DELETE_CARD } from "./fileStreamDeleteConfig"
import { ACCESS_VOLUME_HEADER, ACCESS_VOLUME_CARD } from "./accessVolumeConfig"
import { POWERSHELL_HEADER, POWERSHELL_CARD } from "./powershellConfig"
import { REGKEY_CREATE_HEADER, REGKEY_CREATE_CARD } from "./regKeyCreateConfig"
import { REGKEY_RENAME_HEADER, REGKEY_RENAME_CARD } from "./regKeyRenameConfig"
import { REGKEY_DELETE_HEADER, REGKEY_DELETE_CARD } from "./regKeyDeleteConfig"
import { REGVALUE_SET_HEADER, REGVALUE_SET_CARD } from "./regValueSetConfig"
import { REGVALUE_DELETE_HEADER, REGVALUE_DELETE_CARD } from "./regValueDeleteConfig"
import { REGVALUE_QUERY_HEADER, REGVALUE_QUERY_CARD } from "./regValueQueryConfig"
import { FILEMAPPING_CREATE_HEADER, FILEMAPPING_CREATE_CARD } from "./fileMappingCreateConfig"
import { FILEMAPPING_CONNECT_HEADER, FILEMAPPING_CONNECT_CARD } from "./fileMappingConnectConfig"
import { PIPE_CREATE_HEADER, PIPE_CREATE_CARD } from "./pipeCreateConfig"
import { PIPE_CONNECT_HEADER, PIPE_CONNECT_CARD } from "./pipeConnectConfig"
import { MAILSLOT_CREATE_HEADER, MAILSLOT_CREATE_CARD } from "./mailSlotCreateConfig"
import { MAILSLOT_CONNECT_HEADER, MAILSLOT_CONNECT_CARD } from "./mailSlotConnectConfig"

export {
  PROCESS_CREATE_HEADER,
  PROCESS_CREATE_CARD,
  PROCESS_EXIT_HEADER,
  PROCESS_EXIT_CARD,
  PROCESS_ACCESS_HEADER,
  PROCESS_ACCESS_CARD,
  REMOTE_THREAD_HEADER,
  REMOTE_THREAD_CARD,
  CROSS_MEMORY_EXECUTE_HEADER,
  CROSS_MEMORY_EXECUTE_CARD,
  DNS_HEADER,
  DNS_CARD,
  NET_COMMUNICATE_HEADER,
  NET_COMMUNICATE_CARD,
  SERVICE_CREATE_HEADER,
  SERVICE_CREATE_CARD,
  SERVICE_START_HEADER,
  SERVICE_START_CARD,
  SERVICE_DELETE_HEADER,
  SERVICE_DELETE_CARD,
  SERVICE_STOP_HEADER,
  SERVICE_STOP_CARD,
  SERVICE_CONFIG_HEADER,
  SERVICE_CONFIG_CARD,
  SERVICE_PAUSE_HEADER,
  SERVICE_PAUSE_CARD,
  DEVICE_CHANGE_HEADER,
  DEVICE_CHANGE_CARD,
  DRIVER_IMAGE_LOAD_HEADER,
  DRIVER_IMAGE_LOAD_CARD,
  DLL_IMAGE_LOAD_HEADER,
  DLL_IMAGE_LOAD_CARD,
  TASK_CREATE_HEADER,
  TASK_CREATE_CARD,
  TASK_DELETE_HEADER,
  TASK_DELETE_CARD,
  WMI_QUERY_HEADER,
  WMI_QUERY_CARD,
  WMI_CREATE_CLASS_HEADER,
  WMI_CREATE_CLASS_CARD,
  WMI_FILTER_HEADER,
  WMI_FILTER_CARD,
  WMI_CONSUMER_HEADER,
  WMI_CONSUMER_CARD,
  WMI_BINDING_HEADER,
  WMI_BINDING_CARD,
  WMI_EXECUTE_HEADER,
  WMI_EXECUTE_CARD,
  BITS_CREATE_JOB_HEADER,
  BITS_CREATE_JOB_CARD,
  BITS_JOB_ADD_FILE_HEADER,
  BITS_JOB_ADD_FILE_CARD,
  BITS_JOB_CHANGE_STATE_HEADER,
  BITS_JOB_CHANGE_STATE_CARD, 
  WINDOWS_MESSAGE_HOOK_HEADER,
  WINDOWS_MESSAGE_HOOK_CARD,
  ENCRYPT_DECRYPT_HEADER,
  ENCRYPT_DECRYPT_CARD,
  TOKEN_ADJUST_PRIVILEGE_HEADER,
  TOKEN_ADJUST_PRIVILEGE_CARD,
  TOKEN_IMPERSONATION_HEADER,
  TOKEN_IMPERSONATION_CARD, 
  CREATE_PROCESS_SET_TOKEN_HEADER,
  CREATE_PROCESS_SET_TOKEN_CARD,
  STEALING_CREDENTIALS_HEADER,
  STEALING_CREDENTIALS_CARD,
  FILE_CREATE_HEADER,
  FILE_CREATE_CARD,
  FILE_DELETE_HEADER,
  FILE_DELETE_CARD,
  FILE_CHANGE_ATTRIBUTES_HEADER,
  FILE_CHANGE_ATTRIBUTES_CARD,
  FILE_RENAME_HEADER,
  FILE_RENAME_CARD,
  FILE_MOVE_HEADER,
  FILE_MOVE_CARD,
  FILE_READ_HEADER,
  FILE_READ_CARD,
  FILE_WRITE_HEADER,
  FILE_WRITE_CARD,
  FILE_SET_EA_HEADER,
  FILE_SET_EA_CARD,
  FILE_STREAM_CREATE_HEADER,
  FILE_STREAM_CREATE_CARD,
  FILE_STREAM_DELETE_HEADER,
  FILE_STREAM_DELETE_CARD,
  ACCESS_VOLUME_HEADER,
  ACCESS_VOLUME_CARD,
  POWERSHELL_HEADER,
  POWERSHELL_CARD,
  REGKEY_CREATE_HEADER,
  REGKEY_CREATE_CARD,
  REGKEY_RENAME_HEADER,
  REGKEY_RENAME_CARD,
  REGKEY_DELETE_HEADER,
  REGKEY_DELETE_CARD,
  REGVALUE_SET_HEADER,
  REGVALUE_SET_CARD,
  REGVALUE_DELETE_HEADER,
  REGVALUE_DELETE_CARD,
  REGVALUE_QUERY_HEADER,
  REGVALUE_QUERY_CARD,
  FILEMAPPING_CREATE_HEADER,
  FILEMAPPING_CREATE_CARD,
  FILEMAPPING_CONNECT_HEADER,
  FILEMAPPING_CONNECT_CARD,
  PIPE_CREATE_HEADER,
  PIPE_CREATE_CARD,
  PIPE_CONNECT_HEADER,
  PIPE_CONNECT_CARD,
  MAILSLOT_CREATE_HEADER,
  MAILSLOT_CREATE_CARD,
  MAILSLOT_CONNECT_HEADER,
  MAILSLOT_CONNECT_CARD,
}
