"use client"

import { PROCESS_CREATE_HEADER, PROCESS_CREATE_CARD } from "./processCreateConfig"
import { PROCESS_EXIT_HEADER, PROCESS_EXIT_CARD } from "./processExitConfig"
import { PROCESS_ACCESS_HEADER, PROCESS_ACCESS_CARD } from "./processAccessConfig"
import { REMOTE_THREAD_HEADER, REMOTE_THREAD_CARD } from "./remoteThreadConfig"
import { CROSS_MEMORY_EXECUTE_HEADER, CROSS_MEMORY_EXECUTE_CARD } from "./crossMemoryExecuteConfig"
import { DNS_HEADER, DNS_CARD } from "./dnsConfig"
import { NET_COMMUNICATE_HEADER, NET_COMMUNICATE_CARD } from "./netComunicateConfig"
import { SERVICE_CREATE_HEADER, SERVICE_CREATE_CARD } from "./serviceCreateConfig"
import { SERVICE_START_HEADER,SERVICE_START_CARD } from "./serviceStartConfig"
import { SERVICE_DELETE_HEADER, SERVICE_DELETE_CARD } from "./serviceDeleteConfig"
import { SERVICE_STOP_HEADER, SERVICE_STOP_CARD } from "./serviceStopConfig"
import { SERVICE_CONFIG_HEADER, SERVICE_CONFIG_CARD } from "./serviceConfigConfig"
import { SERVICE_PAUSE_HEADER, SERVICE_PAUSE_CARD } from "./servicePauseConfig"
import { DEVICE_CHANGE_HEADER, DEVICE_CHANGE_CARD } from "./deviceChangeConfig"
import { DRIVER_IMAGE_LOAD_HEADER, DRIVER_IMAGE_LOAD_CARD } from "./driverImageLoadConfig"
import { DLL_IMAGE_LOAD_HEADER, DLL_IMAGE_LOAD_CARD } from "./dllImageLoadConfig"
import { TASK_CREATE_HEADER, TASK_CREATE_CARD } from "./taskCreateConfig"
import { TASK_DELETE_HEADER, TASK_DELETE_CARD } from "./taskDeleteConfig"
import { WMI_QUERY_HEADER, WMI_QUERY_CARD } from "./wmiQueryConfig"

export {
  PROCESS_CREATE_HEADER,
  PROCESS_CREATE_CARD,
  PROCESS_EXIT_HEADER,
  PROCESS_EXIT_CARD,
  PROCESS_ACCESS_HEADER,
  PROCESS_ACCESS_CARD,
  REMOTE_THREAD_HEADER,
  REMOTE_THREAD_CARD,
  CROSS_MEMORY_EXECUTE_HEADER,
  CROSS_MEMORY_EXECUTE_CARD,
  DNS_HEADER,
  DNS_CARD,
  NET_COMMUNICATE_HEADER,
  NET_COMMUNICATE_CARD,
  SERVICE_CREATE_HEADER,
  SERVICE_CREATE_CARD,
  SERVICE_START_HEADER,
  SERVICE_START_CARD,
  SERVICE_DELETE_HEADER,
  SERVICE_DELETE_CARD,
  SERVICE_STOP_HEADER,
  SERVICE_STOP_CARD,
  SERVICE_CONFIG_HEADER,
  SERVICE_CONFIG_CARD,
  SERVICE_PAUSE_HEADER,
  SERVICE_PAUSE_CARD,
  DEVICE_CHANGE_HEADER,
  DEVICE_CHANGE_CARD,
  DRIVER_IMAGE_LOAD_HEADER,
  DRIVER_IMAGE_LOAD_CARD,
  DLL_IMAGE_LOAD_HEADER,
  DLL_IMAGE_LOAD_CARD,
  TASK_CREATE_HEADER,
  TASK_CREATE_CARD,
  TASK_DELETE_HEADER,
  TASK_DELETE_CARD,
  WMI_QUERY_HEADER,
  WMI_QUERY_CARD,
}
